#!/bin/bash

while read -r b1 b2; do
    n1=${#b1} n2=${#b2}
    len1=$(( n1 > len1 ? n1 : len1))
    len2=$(( n2 > len2 ? n2 : len2))
done < <(git branch --format='%(refname:short) %(upstream:short)')


branch="
%(if:equals=*) %(HEAD) %(then)
    *%20%(color:green)
%(else)
    %(if) %(worktreepath) %(then)
        +%20%(color:cyan)
    %(else)
        %20%20
    %(end)
%(end)

%(align:$len1)
    %(refname:short)
%(end)

%(color:reset)
"

upstream="
%(if:equals=[gone]) %(upstream:track) %(then)
    XX
%(else)
    %(upstream:trackshort)
%(end)
"

columns=(
    "%(creatordate:format:%Y-%m-%d)"
    "${branch//[[:space:]]/}"
    "%(color:bold blue)%(align:2)${upstream//[[:space:]]/}%(end)%(color:reset)"
    "%(color:red)%(align:$len2)%(upstream:short)%(end)%(color:reset)"
    "%(color:yellow)%(objectname:short=10)%(color:reset)"
    "%(subject)"
)

git branch --sort='-creatordate' --format="${columns[*]}"
