#!/usr/bin/env zsh
# Show a log of commits unique to the given branch (or HEAD)
# usage: git uniquelog [log options] [branch]

if (( $# == 0 )) || [[ $@[-1] = -* ]]; then
    branch=HEAD
    logopts=( $@ )
else
    branch=$@[-1]
    logopts=( $@[1,-2] )
fi

branch=$(git rev-parse --symbolic-full-name $branch)

format="%(if:equals=$branch)%(refname)%(then)%(refname)%(else)^%(refname)%(end)"
eval "branches=($(git for-each-ref --shell --format="$format" 'refs/heads/**' 'refs/remotes/**'))"

git log $logopts $branches
